version: "3.9"

services:
    php1:
        container_name: php1
        image: php
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - ./src/php:/var/www/html/
        ports:
            - "5001:80"
    php2:
        container_name: php2
        image: php
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - ./src/php:/var/www/html/
        ports:
            - "5002:80"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - php1
            - php2